#redis:
#    image: redis:3.2.6
extimulate:
    build: extimulate
    links:
#        - redis
        - cache2
    volumes:
        - ./extimulate:/extimulate
    environment:
        UPSTREAM_HOST: "cache2"
    command: dumb-init python -m extimulate
cache1:
    image: klokantech/varnish:latest
    volumes:
        - ./cache1/default.vcl:/etc/varnish/default.vcl
    ports:
        - "80:80"
    links:
        - extimulate
cache2:
    image: klokantech/varnish:latest
    volumes:
        - ./cache2/default.vcl:/etc/varnish/default.vcl
